import fs from 'fs'
import path from 'path'

interface WeatherConfig {
  provider: 'open-meteo' | 'openweathermap'
  apiKey: string
  latitude: number
  longitude: number
  locationName: string
  units: 'metric' | 'imperial'
}

interface AppConfig {
  defaultMode: 'slideshow' | 'slideshow-weather' | 'video-wall'
  slideshowInterval: number
  showModeSwitcher: boolean
  weather: WeatherConfig
  videoWall: { videos: string[] }
}

const CONFIG_FILE = path.join(process.cwd(), 'config.json')
const OUTPUT_FILE = path.join(process.cwd(), 'src/generated/app-config.ts')

function parseVideoId(urlOrId: string): string {
  try {
    const url = new URL(urlOrId)
    if (url.hostname === 'youtu.be') return url.pathname.slice(1)
    if (url.hostname === 'www.youtube.com' || url.hostname === 'youtube.com') {
      return url.searchParams.get('v') ?? urlOrId.trim()
    }
  } catch {
    // not a URL — treat as raw video ID
  }
  return urlOrId.trim()
}

function buildConfig(): void {
  const raw = fs.existsSync(CONFIG_FILE)
    ? (JSON.parse(fs.readFileSync(CONFIG_FILE, 'utf-8')) as Partial<AppConfig>)
    : {}

  const cfg: AppConfig = {
    defaultMode: raw.defaultMode ?? 'slideshow',
    slideshowInterval: raw.slideshowInterval ?? 10,
    showModeSwitcher: raw.showModeSwitcher ?? false,
    weather: {
      provider: raw.weather?.provider ?? 'open-meteo',
      apiKey: raw.weather?.apiKey ?? '',
      latitude: raw.weather?.latitude ?? 51.5074,
      longitude: raw.weather?.longitude ?? -0.1278,
      locationName: raw.weather?.locationName ?? 'Unknown',
      units: raw.weather?.units ?? 'metric',
    },
    videoWall: {
      videos: (raw.videoWall?.videos ?? []).map(parseVideoId),
    },
  }

  if (cfg.weather.provider === 'openweathermap' && !cfg.weather.apiKey) {
    console.warn(
      'WARNING: weather.provider is "openweathermap" but no apiKey is set in config.json',
    )
  }

  const outputDir = path.dirname(OUTPUT_FILE)
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true })
  }

  const content = `// Auto-generated by scripts/build-config.ts — do not edit
export type Mode = 'slideshow' | 'slideshow-weather' | 'video-wall'
export type WeatherProvider = 'open-meteo' | 'openweathermap'
export type Units = 'metric' | 'imperial'

export const defaultMode: Mode = ${JSON.stringify(cfg.defaultMode)}
export const slideshowInterval: number = ${cfg.slideshowInterval}
export const showModeSwitcher: boolean = ${cfg.showModeSwitcher}

export const weather = {
  provider: ${JSON.stringify(cfg.weather.provider)} as WeatherProvider,
  apiKey: ${JSON.stringify(cfg.weather.apiKey)},
  latitude: ${cfg.weather.latitude},
  longitude: ${cfg.weather.longitude},
  locationName: ${JSON.stringify(cfg.weather.locationName)},
  units: ${JSON.stringify(cfg.weather.units)} as Units,
}

export const videoIds: string[] = ${JSON.stringify(cfg.videoWall.videos, null, 2)}
`

  fs.writeFileSync(OUTPUT_FILE, content)
  console.log(
    `Generated app config (mode: ${cfg.defaultMode}, ${cfg.videoWall.videos.length} video(s))`,
  )
}

buildConfig()
