import sharp from 'sharp'
import fs from 'fs'
import path from 'path'

interface PhotoMeta {
  filename: string
  width: number
  height: number
  orientation: 'landscape' | 'portrait'
}

const PHOTOS_DIR = path.join(process.cwd(), 'photos')
const OUTPUT_FILE = path.join(process.cwd(), 'src/generated/photo-manifest.ts')
const SUPPORTED_EXTS = new Set(['.jpg', '.jpeg', '.png'])

async function buildManifest(): Promise<void> {
  const photos: PhotoMeta[] = []

  if (fs.existsSync(PHOTOS_DIR)) {
    const files = fs.readdirSync(PHOTOS_DIR).sort()

    for (const file of files) {
      const ext = path.extname(file).toLowerCase()
      if (!SUPPORTED_EXTS.has(ext)) continue

      const filePath = path.join(PHOTOS_DIR, file)
      try {
        const meta = await sharp(filePath).metadata()
        let width = meta.width ?? 0
        let height = meta.height ?? 0

        // EXIF orientations 5–8 indicate a 90° rotation — swap axes
        const exifOrientation = meta.orientation ?? 1
        if (exifOrientation >= 5 && exifOrientation <= 8) {
          ;[width, height] = [height, width]
        }

        photos.push({
          filename: file,
          width,
          height,
          orientation: width > height ? 'landscape' : 'portrait',
        })
      } catch (err) {
        console.warn(`Skipping ${file}: ${err}`)
      }
    }
  }

  const outputDir = path.dirname(OUTPUT_FILE)
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true })
  }

  const content = `// Auto-generated by scripts/build-manifest.ts — do not edit
export interface PhotoMeta {
  filename: string
  width: number
  height: number
  orientation: 'landscape' | 'portrait'
}

export const photos: PhotoMeta[] = ${JSON.stringify(photos, null, 2)}
`

  fs.writeFileSync(OUTPUT_FILE, content)
  console.log(`Generated photo manifest with ${photos.length} photo(s)`)
}

buildManifest().catch((err) => {
  console.error('build-manifest failed:', err)
  process.exit(1)
})
